export const carData = [
    {
        company: "BMW",
        model: "X1",
        body: "SUV",
        fuel: "Petrol & Diesel",
        seating: 5,
        price: "41.43 lakhs",
        economy: 14.82,
        engine: "1995 to 1998",
        power: "188 to 189",
    },
    {
        company: "BMW",
        model: "X3",
        body: "SUV",
        fuel: "Petrol",
        seating: 5,
        price: "61.90 lakhs",
        economy: 13.17,
        engine: "1995 to 1998",
        power: "188 to 248",
    },
    {
        company: "BMW",
        model: "3 Series",
        body: "Sedan",
        fuel: "Petrol & Diesel",
        seating: 5,
        price: "46.90 lakhs",
        economy: 20.37,
        engine: "1995 to 2998",
        power: "188 to 382",
    },
    {
        company: "BMW",
        model: "X5",
        body: "SUV",
        fuel: "Petrol & Diesel",
        seating: 5,
        price: "79.90 lakhs",
        economy: 13.38,
        engine: "2993 to 2998",
        power: "262 to 335",
    },
    {
        company: "BMW",
        model: "Z4",
        body: "Convertible",
        fuel: "Petrol",
        seating: 2,
        price: "71.90 lakhs",
        economy: 14.37,
        engine: "1998 to 2998",
        power: "194 to 375",
    },
    {
        company: "BMW",
        model: "7 Series",
        body: "Sedan",
        fuel: "Petrol & Diesel",
        seating: 4,
        price: "1.42 cr",
        economy: 17.66,
        engine: "2995 to 2998",
        power: "262 to 389",
    },
    {
        company: "BMW",
        model: "X7",
        body: "SUV",
        fuel: "Petrol & Diesel",
        seating: 7,
        price: "1.18 cr",
        economy: 12.04,
        engine: "2993 to 2998",
        power: "262 to 394",
    },
    {
        company: "BMW",
        model: "iX",
        body: "SUV",
        fuel: "Electric",
        seating: 5,
        price: "1.16 cr",
        economy: null,
        engine: null,
        power: null,
    },
    {
        company: "Mercedes Benz",
        model: "A Class Limousine",
        body: "Sedan",
        fuel: "Petrol & Diesel",
        seating: 5,
        price: "41.99 lakhs",
        economy: 21.35,
        engine: "1332 to 1598",
        power: "141 to 161",
    },
    {
        company: "Mercedes Benz",
        model: "GLA",
        body: "SUV",
        fuel: "Petrol & Diesel",
        seating: 5,
        price: "44.99 lakhs",
        economy: 17.5,
        engine: "1335 to 1950",
        power: "161 to 188",
    },
    {
        company: "Mercedes Benz",
        model: "GLE",
        body: "SUV",
        fuel: "Diesel",
        seating: 5,
        price: "85.73 lakhs",
        economy: 13.89,
        engine: "1995 to 2998",
        power: "241 to 326",
    },
    {
        company: "Mercedes Benz",
        model: "Maybach S Class",
        body: "Sedan",
        fuel: "Petrol & Mild Hybrid",
        seating: 5,
        price: "2.50 cr",
        economy: 9.8,
        engine: "3992 to 5980",
        power: "496 to 603",
    },
    {
        company: "Mercedes Benz",
        model: "V Class",
        body: "Minivan",
        fuel: "Diesel",
        seating: 7,
        price: "71.90 lakhs",
        economy: 16.39,
        engine: "1995",
        power: "161",
    },
]